###
GET http://localhost:8080/books/39858cea-5286-434c-a5d6-4a8c31eb5fe4

###
POST http://localhost:8080/books/
Content-Type: application/json

{
  "title": "Workshop - Spring Boot Starter Web",
  "release": "2023-11-27T00:00:00"
}


###
GET http://localhost:8080/books/

###
DELETE http://localhost:8080/books/39858cea-5286-434c-a5d6-4a8c31eb5fe4

###
PATCH http://localhost:8080/books/7f545733-0257-4a4d-89b2-1675e38b4774
Content-Type: application/json

{
  "title": "Workshop - Spring Boot Starter Web",
  "author": {
    "name": "Fabio",
    "surname": "Maruca"
  },
  "release": "2023-11-27T00:00:00"
}
